# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: nadeem-afana

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-18249804-1

# Setup
title:            Nadeem Afana's Blog
tagline:          Home
description:      Nadeem Afana
url:              https://nadeemafana.github.io
baseurl:          /

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/677513?v=3&s=180

author:
  name:           'Nadeem Afana'
  url:            http://afana.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

permalink: archive/:year/:month/:day/:title/
paginate: 5
paginate_path: "page/:num"

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem  
  - jekyll-redirect-from